# Generated by Django 2.2.4 on 2020-05-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(default='None Entered', max_length=75)),
                ('quantity_bought', models.FloatField()),
                ('cost', models.FloatField()),
                ('buy_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.FloatField()),
                ('amount', models.FloatField()),
                ('sold_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock_buy')),
            ],
        ),
    ]
