# Generated by Django 2.2.4 on 2020-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_buy',
            name='buy_date',
            field=models.DateField(blank=True),
        ),
    ]
